before_install: sudo apt-get -qq update
install: sudo apt-get install -y cmake make
cache: cmake make
language: cpp
branches:
    only:
        - testing
        - stable
compiler:
  - clang
  - gcc
script:
  - cmake .
  - make vulkalc && make vulkalc-test
  - cd vulkalc-tests
  - ./vulkalc-test