before_install: sudo apt-get -qq update
install: sudo apt-get install -y cmake make
cache: cmake make
language: cpp
compiler:
  - clang
  - gcc
script:
  - cmake .
  - make vulkalc && make vulkalc-tests
  - cd vulkalc-tests
  - ls
